# Generated by Django 3.2.14 on 2022-07-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_menu_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
